services:
  web:
    build: .
    image: demo-website:latest
    container_name: demo-website
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      NODE_ENV: production
      API_BASE_URL: "http://api:8000"
    networks:
      - demo-rest_default
      - default
    restart: unless-stopped

networks:
  demo-rest_default:
    external: true
